apiVersion : apps/v1
kind: Deployment
metadata:
  name: tmapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tmapi
  template:
    metadata:
      labels:
        app: tmapi 
    spec:
      containers:
        - name: tmapi 
          image: fengchuandevcontainer.azurecr.io/tmapi
          ports:
          - containerPort: 8000